---
- name: Install Bind9
  apt:
    name: bind9
    state: present

- name: Install named.conf.local into /etc/bind
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Reload Bind.

# TODO: Got to here to validate comparison with lug.org.uk
- name: Create zone files ready to inject into /etc/bind
  changed_when: false
  template:
    src: db.DNSNAME.j2
    dest: "/etc/bind/tmp_db.{{ item }}"
  vars:
    my: "{{ dns[item] }}"
  loop:
  - lug.org.uk
  - ogg.camp
  notify: Reload Bind.

- name: Verify then replace changed zone files
  # This extra step is required because the template creates a "serial" which is actually just the date and time.
  # This script diffs the two files without the serial line, and if there are differences, it copies the "temporary" version over the "target".
  shell: "bash /etc/ansible/install/roles/lugorguk.bind/files/validate-bind-db.sh /etc/bind/tmp_db.{{ item }} /etc/bind/db.{{ item }}"
  register: output
  changed_when: output.rc == 1
  failed_when: output.rc == 2
  loop:
  - lug.org.uk
  - ogg.camp
  notify: Reload Bind.

- name: Make /etc/bind/reverse directory
  file:
    path: /etc/bind/reverse
    state: directory
    owner: root
    group: bind
    mode: '0755'

- name: Create reverse IPv6 zone bind records
  template:
    src: reverse-db.ipv6.j2
    dest: "/etc/bind/reverse/tmp_db.{{ item.key }}-ipv6"
  changed_when: false
  loop: "{{ hosts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Verify then replace changed zone files
  shell: "bash /etc/ansible/install/roles/lugorguk.bind/files/validate-bind-db.sh /etc/bind/reverse/tmp_db.{{ item.key }}-ipv6 /etc/bind/reverse/db.{{ item.key }}-ipv6"
  register: output
  changed_when: output.rc == 1
  failed_when: output.rc == 2
  loop: "{{ hosts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Reload Bind.
