---
- name: Install Bind9 and Dig
  apt:
    name:
    - bind9
    - dnsutils
    state: present

- name: Config apparmor to permit bind logging
  lineinfile:
    path: /etc/apparmor.d/local/usr.sbin.named
    line: "  /var/log/named.log rw,"
  notify: Reload AppArmor.

- name: Check bind log state
  stat:
    path: /var/log/named.log
  register: stat

- name: Create bind log file
  when: not stat.stat.exists
  file:
    path: /var/log/named.log
    state: touch
    owner: bind
    group: root
    mode: "0640"
  notify: Reload Bind.

- name: Install named.conf files into /etc/bind
  template:
    src: "named.conf.{{ item }}.j2"
    dest: "/etc/bind/named.conf.{{ item }}"
    owner: root
    group: bind
    mode: "0644"
  notify: Reload Bind.
  loop:
  - local
  - options
  loop_control:
    label: "named.conf.{{ item }}"

# FIXME: `/usr/sbin/named-checkconf -z "/etc/bind/named.conf"` fails with lots of issues!
- name: Create zone files ready to inject into /etc/bind
  changed_when: false
  template:
    src: db.DNSNAME.j2
    dest: "/etc/bind/tmp_db.{{ item }}"
    owner: root
    group: bind
    mode: "0644"
  vars:
    my: "{{ dns[item] }}"
  loop:
  - lug.org.uk
  - ogg.camp

- name: Verify then replace changed zone files
  # This extra step is required because the template creates a "serial" which is actually just the date and time.
  # This script diffs the two files without the serial line, and if there are differences, it copies the "temporary" version over the "target".
  shell: "bash -x /etc/ansible/install/roles/lugorguk.bind/files/validate-bind-db.sh /etc/bind/tmp_db.{{ item }} /etc/bind/db.{{ item }} CHECK_BINDCONF"
  register: output
  changed_when: output.rc == 1
  failed_when: output.rc == 2
  loop:
  - lug.org.uk
  - ogg.camp
  notify: Reload Bind.

- name: Make /etc/bind/reverse directory
  file:
    path: /etc/bind/reverse
    state: directory
    owner: root
    group: bind
    mode: '0755'

- name: Create reverse IPv6 zone bind records
  template:
    src: reverse-db.ipv6.j2
    dest: "/etc/bind/reverse/tmp_db.{{ item.key }}-ipv6"
    owner: root
    group: bind
    mode: "0644"
  changed_when: false
  loop: "{{ hosts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Verify then replace changed zone files
  shell: "bash -x /etc/ansible/install/roles/lugorguk.bind/files/validate-bind-db.sh /etc/bind/reverse/tmp_db.{{ item.key }}-ipv6 /etc/bind/reverse/db.{{ item.key }}-ipv6 CHECK_BINDCONF"
  register: output
  changed_when: output.rc == 1
  failed_when: output.rc == 2
  loop: "{{ hosts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Reload Bind.
